from __future__ import annotations
from alembic import op
import sqlalchemy as sa
revision="0001_web_v05";down_revision=None;branch_labels=None;depends_on=None

def upgrade()->None:
 op.create_table("users",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("username",sa.String(128),nullable=False),sa.Column("password_hash",sa.Text(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("is_admin",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("username",name="uq_users_username"));op.create_index("ix_users_username","users",["username"],unique=True)
 op.create_table("sessions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.BigInteger(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("token_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True),nullable=True),sa.UniqueConstraint("token_hash",name="uq_sessions_token_hash"));op.create_index("ix_sessions_user_id","sessions",["user_id"]);op.create_index("ix_sessions_token_hash","sessions",["token_hash"],unique=True);op.create_index("ix_sessions_expires_at","sessions",["expires_at"])
 op.create_table("imports",sa.Column("id",sa.String(36),primary_key=True),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("filename",sa.String(255),nullable=False),sa.Column("imported_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("imported_by",sa.BigInteger(),sa.ForeignKey("users.id"),nullable=False),sa.Column("repeated_of_id",sa.String(36),sa.ForeignKey("imports.id"),nullable=True),sa.Column("new_events",sa.Integer(),nullable=False,server_default="0"),sa.Column("duplicate_events",sa.Integer(),nullable=False,server_default="0"),sa.Column("rejected_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("row_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("unique_kiz",sa.Integer(),nullable=False,server_default="0"),sa.Column("sales",sa.Integer(),nullable=False,server_default="0"),sa.Column("returns",sa.Integer(),nullable=False,server_default="0"),sa.Column("dated",sa.Integer(),nullable=False,server_default="0"),sa.Column("undated",sa.Integer(),nullable=False,server_default="0"));op.create_index("ix_imports_fingerprint","imports",["fingerprint"])
 op.create_table("events",sa.Column("event_id",sa.String(64),primary_key=True),sa.Column("kiz",sa.Text(),nullable=False),sa.Column("task_number",sa.Text(),nullable=False),sa.Column("sticker",sa.Text(),nullable=False),sa.Column("operation",sa.String(16),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=True),sa.Column("receipt_number",sa.Text(),nullable=True),sa.Column("fiscal_drive_number",sa.Text(),nullable=True),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("legal_entity_sale",sa.Boolean(),nullable=True),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_events_kiz","events",["kiz"]);op.create_index("ix_events_occurred_at","events",["occurred_at"])
 op.create_table("import_rows",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("import_id",sa.String(36),sa.ForeignKey("imports.id",ondelete="CASCADE"),nullable=False),sa.Column("row_number",sa.Integer(),nullable=False),sa.Column("event_id",sa.String(64),sa.ForeignKey("events.event_id"),nullable=True),sa.Column("error",sa.Text(),nullable=True),sa.UniqueConstraint("import_id","row_number",name="uq_import_row_number"));op.create_index("ix_import_rows_import_id","import_rows",["import_id"]);op.create_index("ix_import_rows_event_id","import_rows",["event_id"])
 op.create_table("control_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("import_id",sa.String(36),sa.ForeignKey("imports.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.BigInteger(),sa.ForeignKey("users.id"),nullable=False),sa.Column("mode",sa.String(32),nullable=False),sa.Column("provider",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_control_runs_import_id","control_runs",["import_id"])
 op.create_table("checks",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("run_id",sa.String(36),sa.ForeignKey("control_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("event_id",sa.String(64),sa.ForeignKey("events.event_id",ondelete="CASCADE"),nullable=False),sa.Column("source",sa.String(64),nullable=False),sa.Column("snapshot",sa.JSON(),nullable=True),sa.Column("decision",sa.String(32),nullable=False),sa.Column("reason",sa.String(96),nullable=False),sa.Column("error",sa.Text(),nullable=True),sa.Column("checked_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_checks_run_id","checks",["run_id"]);op.create_index("ix_checks_event_id","checks",["event_id"]);op.create_index("ix_checks_decision","checks",["decision"])
 op.create_table("previews",sa.Column("id",sa.String(36),primary_key=True),sa.Column("import_id",sa.String(36),sa.ForeignKey("imports.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.BigInteger(),sa.ForeignKey("users.id"),nullable=False),sa.Column("mode",sa.String(32),nullable=False),sa.Column("selected_count",sa.Integer(),nullable=False),sa.Column("eligible_count",sa.Integer(),nullable=False),sa.Column("withdraw_count",sa.Integer(),nullable=False),sa.Column("return_count",sa.Integer(),nullable=False),sa.Column("excluded_count",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_previews_import_id","previews",["import_id"])
 op.create_table("preview_items",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("preview_id",sa.String(36),sa.ForeignKey("previews.id",ondelete="CASCADE"),nullable=False),sa.Column("event_id",sa.String(64),sa.ForeignKey("events.event_id"),nullable=False),sa.Column("included",sa.Boolean(),nullable=False),sa.Column("decision",sa.String(32),nullable=True),sa.Column("reason",sa.String(96),nullable=True));op.create_index("ix_preview_items_preview_id","preview_items",["preview_id"])
 op.create_table("audit_log",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("action",sa.String(64),nullable=False),sa.Column("user_id",sa.BigInteger(),sa.ForeignKey("users.id"),nullable=True),sa.Column("entity_type",sa.String(32),nullable=True),sa.Column("entity_id",sa.String(128),nullable=True),sa.Column("metadata_json",sa.JSON(),nullable=False));op.create_index("ix_audit_log_occurred_at","audit_log",["occurred_at"]);op.create_index("ix_audit_log_action","audit_log",["action"])

def downgrade()->None:
 for table in ("audit_log","preview_items","previews","checks","control_runs","import_rows","events","imports","sessions","users"):op.drop_table(table)
