import {api,upload} from './api.js'
import type {ImportItem,EventItem} from './types'

const app=document.querySelector<HTMLDivElement>('#app')!
let current:any=null, events:EventItem[]=[], selected=new Set<string>(), filter='all', query='', checking=false, preview:any=null, detail:string|null=null
const decLabel:Record<string,string>={READY_TO_WITHDRAW:'Нужно вывести',READY_TO_RETURN:'Нужно вернуть',ALREADY_DONE:'Уже обработано',MANUAL_REVIEW:'Требует проверки',ERROR:'Ошибка'}
const reasonLabel:Record<string,string>={OTHER_OWNER:'Другой владелец',NON_DISTANCE_OR_UNKNOWN_WITHDRAWAL:'Другая причина выбытия',STATE_LOOKUP_OR_NORMALIZATION_FAILED:'Нет ответа локальной проверки',SALE_ALREADY_WITHDRAWN_DISTANCE:'Уже выведен из оборота',RETURN_ALREADY_IN_CIRCULATION:'Уже в обороте'}
const fmt=(s:string)=>new Date(s).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'})
const date=(s:string|null)=>s?new Date(s).toLocaleDateString('ru-RU'):'—'

async function init(){renderShell();await renderHome()}
function renderShell(){app.innerHTML=`<div class="topbar"><div class="brand">markflow</div><div class="profile">MM</div></div><aside class="rail"><button class="rail-btn active" title="FBS WB">◆</button><button class="rail-btn" title="Файлы">▣</button><button class="rail-help" title="Помощь">?</button></aside><main id="main" class="main"></main>`}
function main(){return document.querySelector<HTMLElement>('#main')!}

async function renderHome(){current=null;events=[];selected.clear();preview=null;const imports=await api<ImportItem[]>('/api/imports?limit=10');main().innerHTML=`<div class="page-title"><h1>Вывод и ввод в оборот (FBS WB)</h1><span class="help-dot">?</span></div><section class="upload-zone" id="drop"><input id="file" type="file" accept=".xlsx" hidden><div class="upload-copy"><strong>Перетащите файл сюда</strong><span>или нажмите для выбора</span><small>Поддерживается формат XLSX</small></div></section><section class="recent"><div class="section-head"><h2>Последние файлы</h2></div>${imports.length?historyTable(imports):'<div class="empty-history">Загруженных файлов пока нет</div>'}</section>`;const input=document.querySelector<HTMLInputElement>('#file')!,drop=document.querySelector<HTMLElement>('#drop')!;drop.onclick=()=>input.click();input.onchange=()=>input.files?.[0]&&loadFile(input.files[0]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');const f=e.dataTransfer?.files[0];if(f)loadFile(f)};document.querySelectorAll<HTMLElement>('[data-open]').forEach(x=>x.onclick=()=>openImport(x.dataset.open!))}
function historyTable(items:ImportItem[]){return `<div class="history-wrap"><table class="history"><thead><tr><th>Дата и время</th><th>Имя файла</th><th>Строк</th><th>КИЗ</th><th>Статус</th><th></th></tr></thead><tbody>${items.map(i=>`<tr><td>${fmt(i.uploaded_at)}</td><td class="file-name"><span class="xlsx">X</span>${esc(i.filename)}</td><td>${i.row_count}</td><td>${i.unique_kiz}</td><td>${i.repeated?'<span class="status repeat">Повторно загружен · новых 0</span>':i.status==='processed'?'<span class="status ok">Обработан</span>':'<span class="status bad">Ошибка</span>'}</td><td><button class="icon-btn" data-open="${i.fingerprint}" title="Открыть">◉</button></td></tr>`).join('')}</tbody></table></div>`}
async function loadFile(file:File){try{const result=await upload(file);await openImport(result.fingerprint)}catch(e){alert(String(e))}}
async function openImport(fp:string){current=await api<any>(`/api/imports/${fp}`);events=await api<EventItem[]>(`/api/imports/${fp}/events`);selected.clear();preview=null;renderWorkspace()}
function renderWorkspace(){main().innerHTML=`<div class="workspace-head"><div><div class="page-title"><h1>Вывод и ввод в оборот (FBS WB)</h1><span class="help-dot">?</span></div><div class="file-context"><span class="xlsx">X</span><div><strong>${esc(current.filename)}</strong><small>Загружен ${fmt(current.uploaded_at)} · ${current.event_count} строк</small></div></div></div><div class="head-actions"><span class="mode">Тестовый режим</span><button id="replace" class="text-btn">Заменить файл</button></div></div><div class="check-line"><button id="check" class="secondary-btn">${events.some(e=>e.decision)?'Повторить проверку':'Проверить КИЗ'}</button><span id="check-status">${events.some(e=>e.decision)?'Локальная проверка выполнена':'Проверка: локальная'}</span></div><div class="toolbar"><div class="search-wrap">⌕<input id="search" placeholder="Поиск по КИЗ"></div><select id="filter"><option value="all">Все рекомендации</option><option value="READY_TO_WITHDRAW">Нужно вывести</option><option value="READY_TO_RETURN">Нужно вернуть</option><option value="ALREADY_DONE">Уже обработано</option><option value="MANUAL_REVIEW">Требует проверки</option><option value="ERROR">Ошибка</option></select><span class="shown" id="shown"></span></div><div class="table-shell"><table class="events"><thead><tr><th class="check-col"><input id="all" type="checkbox"></th><th>КИЗ</th><th>Операция WB</th><th>Дата WB</th><th>Рекомендация</th><th>Состояние</th><th></th></tr></thead><tbody id="rows"></tbody></table></div><div id="operation"></div>`;document.querySelector('#replace')!.addEventListener('click',renderHome);document.querySelector('#check')!.addEventListener('click',runCheck);document.querySelector<HTMLInputElement>('#search')!.oninput=e=>{query=(e.target as HTMLInputElement).value;renderRows()};document.querySelector<HTMLSelectElement>('#filter')!.onchange=e=>{filter=(e.target as HTMLSelectElement).value;renderRows()};document.querySelector<HTMLInputElement>('#all')!.onchange=e=>{const on=(e.target as HTMLInputElement).checked;visible().forEach(x=>on?selected.add(x.event_id):selected.delete(x.event_id));preview=null;renderRows();renderOperation()};renderRows();renderOperation()}
function visible(){return events.filter(e=>(filter==='all'||e.decision===filter)&&(!query||e.kiz.includes(query.trim())))}
function renderRows(){const body=document.querySelector<HTMLTableSectionElement>('#rows')!;const list=visible();document.querySelector('#shown')!.textContent=`${list.length} из ${events.length}`;body.innerHTML=list.map(e=>`<tr class="${selected.has(e.event_id)?'selected':''}"><td><input data-pick="${e.event_id}" type="checkbox" ${selected.has(e.event_id)?'checked':''}></td><td><code title="${esc(e.kiz)}">${short(e.kiz)}</code></td><td>${e.operation}</td><td>${date(e.occurred_at)}</td><td>${decisionBadge(e)}</td><td>${stateText(e)}</td><td><button class="icon-btn" data-detail="${e.event_id}" title="Подробности">⌄</button></td></tr>${detail===e.event_id?'<tr class="detail-row"><td colspan="7"><div id="detail"></div></td></tr>':''}`).join('');body.querySelectorAll<HTMLInputElement>('[data-pick]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.pick!):selected.delete(x.dataset.pick!);preview=null;renderRows();renderOperation()});body.querySelectorAll<HTMLElement>('[data-detail]').forEach(x=>x.onclick=async()=>{detail=detail===x.dataset.detail?null:x.dataset.detail!;renderRows();if(detail){const d=await api<any>(`/api/events/${detail}`);renderDetail(d)}})}
function decisionBadge(e:EventItem){if(!e.decision)return '<span class="muted">Не проверено</span>';const tone=e.decision==='ERROR'?'danger':e.decision==='MANUAL_REVIEW'?'warn':e.decision==='ALREADY_DONE'?'neutral':'good';return `<span class="badge ${tone}">${decLabel[e.decision]||e.decision}</span>`}
function stateText(e:EventItem){if(e.error)return '<span class="danger-text">Нет ответа</span>';if(e.reason&&e.decision==='MANUAL_REVIEW')return `<span class="warn-text">${reasonLabel[e.reason]||e.reason}</span>`;return e.checked_at?'<span class="muted">Проверено локально</span>':'<span class="muted">—</span>'}
async function renderDetail(d:any){const el=document.querySelector('#detail');if(!el)return;el.innerHTML=`<div class="detail-grid"><section><h3>Полный КИЗ</h3><div class="copy-line"><code>${esc(d.kiz)}</code><button id="copy" class="text-btn">Копировать</button></div></section><section><h3>Событие WB</h3><p>${d.operation} · ${date(d.occurred_at)}</p><p class="muted">Задание ${esc(d.task_number)} · Стикер ${esc(d.sticker)}</p></section><section><h3>Проверка</h3><p>${d.decision?decLabel[d.decision]||d.decision:'Не проверено'}</p><p class="muted">${esc(reasonLabel[d.reason]||d.reason||d.error||'—')}</p></section></div><div class="history-block"><h3>История этого КИЗ</h3>${d.history.map((h:any)=>`<div class="history-event"><span>${h.operation}</span><span>${date(h.occurred_at)}</span><span>${esc(h.task_number)}</span></div>`).join('')}${d.history_order_ambiguous?'<p class="warning-note">Порядок части событий неоднозначен. Интерфейс не выбирает «последнее» событие самостоятельно.</p>':''}</div>`;document.querySelector('#copy')!.addEventListener('click',()=>navigator.clipboard.writeText(d.kiz))}
async function runCheck(){checking=true;const b=document.querySelector<HTMLButtonElement>('#check')!;b.disabled=true;b.textContent='Проверяем…';document.querySelector('#check-status')!.innerHTML='<span class="spinner"></span>Локальная проверка';await api(`/api/imports/${current.fingerprint}/check`,{method:'POST'});events=await api<EventItem[]>(`/api/imports/${current.fingerprint}/events`);checking=false;renderWorkspace()}
function renderOperation(){const op=document.querySelector<HTMLDivElement>('#operation');if(!op)return;if(!selected.size&&!preview){op.innerHTML='';return}const chosen=events.filter(e=>selected.has(e.event_id));const ready=chosen.filter(e=>e.decision==='READY_TO_WITHDRAW'||e.decision==='READY_TO_RETURN');const out=ready.filter(e=>e.decision==='READY_TO_WITHDRAW').length,ret=ready.length-out,excluded=chosen.length-ready.length;op.innerHTML=`<div class="operation-bar"><div class="op-counts"><span><b>${chosen.length}</b><small>Выбрано</small></span><span><b>${ready.length}</b><small>К выполнению</small></span><span><b>${out}</b><small>Вывод</small></span><span><b>${ret}</b><small>Возврат</small></span><span><b>${excluded}</b><small>Исключено</small></span></div><button id="preview" class="primary-btn">Проверить состав</button></div>${preview?previewHtml(preview):''}`;document.querySelector('#preview')!.addEventListener('click',async()=>{preview=await api<any>('/api/operation-preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_ids:[...selected]})});renderOperation()})}
function previewHtml(p:any){const reasons=new Map<string,number>();p.excluded.forEach((x:any)=>reasons.set(x.reason,(reasons.get(x.reason)||0)+1));return `<div class="preview"><div class="preview-head"><div><h2>Проверка состава</h2><p>${esc(current.filename)} · выбран рабочий состав из ${p.selected} событий</p></div><span class="mode">Только preview</span></div><div class="preview-numbers"><span><b>${p.included.length}</b> войдут в состав</span><span><b>${p.withdraw}</b> вывод</span><span><b>${p.returns}</b> возврат</span><span><b>${p.excluded.length}</b> исключено</span></div>${p.excluded.length?`<div class="excluded"><h3>Исключены backend-решением</h3>${[...reasons].map(([r,n])=>`<div><span>${esc(reasonLabel[r]||r)}</span><b>${n}</b></div>`).join('')}</div>`:''}<p class="preview-note">Реальная отправка пока недоступна в тестовом режиме. Этот экран ничего не отправляет.</p></div>`}
function short(s:string){return esc(s.length>36?s.slice(0,22)+'…'+s.slice(-10):s)}
function esc(s:any){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
init()
